### ISSUE TITLE
[bug]: ChartTooltip indicator not rendering

### ISSUE THREAD

**Issue by lalabuy948** [lalabuy948/PhoenixAnalytics#1]
ChartTooltip is not rendering indicator colors. I spent good 2-3 nights debugging but could not find the root cause, unfortunately I don't have deep FE knowledge. Could be something to do with better tailwind config or esbuild 🤷🏻‍♂️ 

<img width="256" alt="360191571-73a147f6-9976-4433-ab05-b49da5d16f37" src="https://github.com/user-attachments/assets/401198b5-6207-4bba-9603-342b8100ff66">

How suppose to be:

<img width="211" alt="Screenshot 2024-09-04 at 00 50 16" src="https://github.com/user-attachments/assets/ec635386-8558-4e00-88a2-60215e1a5ff4">

**Comment by adamroyle** [comment]
@lalabuy948 You need to upgrade to Tailwind 3.3 or higher (when variable shorthand was added) - your Tailwind version is set to 3.2.7

**Comment by lalabuy948** [comment]
ha, you are legend @adamroyle ! The next release is dedicated to you :)

**Comment by lalabuy948** [comment]
🙌🏻

<img width="330" alt="Screenshot 2024-10-09 at 10 48 44" src="https://github.com/user-attachments/assets/7cbd4f6c-5605-4660-bf7d-2bba6dd726b1">

**Comment by adamroyle** [comment]
No worries!
