### ISSUE TITLE
Consider to use `elixir_uuid` instead of `uuid`

### ISSUE THREAD

**Issue by vermaxik** [lalabuy948/PhoenixAnalytics#15]
Thanks for your library, looks really great, tried to use in the dockerized app with mix release, but didn't have a luck with package name coalitions, because already have elixir_uuid from another package.

```bash
using config/runtime.exs to configure the release at runtime
[13:30:03.523] #19 1.850 ** (Mix) Duplicated modules:
[13:30:03.532] #19 1.850 	'Elixir.UUID' specified in elixir_uuid and uuid
[13:30:03.632] #19 ERROR: process "/bin/sh -c mix release" did not complete successfully: exit code: 1
```

Would it possible to upgrade the uuid to elixir_uuid, as recommended https://github.com/zyro/elixir-uuid?

>Note: Renamed from [uuid](https://hex.pm/packages/uuid) to [elixir_uuid](https://hex.pm/packages/elixir_uuid) as a solution to package name conflicts. Use [elixir_uuid](https://hex.pm/packages/elixir_uuid) going forward.

Let me know if I should create PR. Thank you.

**Comment by lalabuy948** [comment]
Hi @vermaxik , 

Thank you for reporting this issue. Could you be so kind to take a look on this [PR](https://github.com/lalabuy948/PhoenixAnalytics/pull/16)?

**Comment by lalabuy948** [comment]
Will close this one. Resoled in [0.1.3](https://github.com/lalabuy948/PhoenixAnalytics/releases/tag/0.1.3)
