### ISSUE TITLE
Update Gettext usage to address deprecation warning

### ISSUE THREAD

**Issue by cbuctok** [lalabuy948/PhoenixAnalytics#6]
## Description

During compilation, the following deprecation warning is encountered:

```
warning: defining a Gettext backend by calling

    use Gettext, otp_app: ...

is deprecated. To define a backend, call:

    use Gettext.Backend, otp_app: :my_app

Then, instead of importing your backend, call this in your module:

    use Gettext, backend: MyApp.Gettext

  lib/phoenix_analytics/web/gettext.ex:4: PhoenixAnalytics.Web.Gettext (module)
```

This warning suggests that our current Gettext implementation is using a deprecated approach.

## Current Implementation

The current implementation uses:

```elixir
defmodule PhoenixAnalytics.Web.Gettext do
  @moduledoc false

  use Gettext, otp_app: :phoenix_analytics
end
```

## Proposed Solution

To resolve this deprecation warning, we should update our Gettext usage as follows:

1. In `lib/phoenix_analytics/web/gettext.ex`:

```elixir
defmodule PhoenixAnalytics.Web.Gettext do
  @moduledoc false

  use Gettext.Backend, otp_app: :phoenix_analytics
end
```

2. In modules where Gettext is currently imported, replace:

```elixir
import PhoenixAnalytics.Web.Gettext
```

with:

```elixir
use Gettext, backend: PhoenixAnalytics.Web.Gettext
```

## Benefits

- Resolves the deprecation warning
- Aligns our codebase with the latest Gettext best practices
- Improves maintainability and future compatibility

## Additional Notes

- This change should be backwards compatible, but thorough testing is recommended after implementation.
- We should review all files that import or use Gettext to ensure complete coverage of this update.

**Comment by lalabuy948** [comment]
Resoled in [0.1.3](https://github.com/lalabuy948/PhoenixAnalytics/releases/tag/0.1.3)
