### ISSUE TITLE
Hosting DuckDB as separate resource?

### ISSUE THREAD

**Issue by jaimeiniesta** [lalabuy948/PhoenixAnalytics#8]
Hi, I'm excited about this project and wanting to try it, but I'm a newbie to DuckDB and I'm not sure how to set it up.

My application is now running in Heroku, one single dyno, but I don't see a plugin for Heroku to handle DuckDB. There's just a buildpack to run it using Ruby.

What's the best approach to run my own DuckDB?

**Comment by lalabuy948** [comment]
Hi @jaimeiniesta, treat duckdb as sqlite. It's a disk persistent database, which is not the best friend for heroku users unfortunately. As I remember heroku ephemeral and doesn't let you store anything on the disk. 

>[Disk backed storage](https://devcenter.heroku.com/articles/sqlite3#disk-backed-storage)

>SQLite runs in memory, and backs up its data store in files on disk. While this strategy works well for development, Heroku’s Cedar stack has an [ephemeral filesystem](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem). You can write to it, and you can read from it, but the contents will be cleared periodically. If you were to use SQLite on Heroku, you would lose your entire database at least once every 24 hours.

>Even if Heroku’s disks were persistent running SQLite would still not be a good fit. Since SQLite does not run as a service, each dyno would run a separate running copy. Each of these copies need their own disk backed store. This would mean that each dyno powering your app would have a different set of data since the disks are not synchronized.

> Instead of using SQLite on Heroku you can configure your app to run on Postgres.

I will work on a solution for that scenario.

**Comment by jaimeiniesta** [comment]
Thanks for looking into alternatives!

Storing in Postgres isn't a big problem to me, I'm already using the main Postgres app for Oban and ErrorTracker and everything works smoothly. I don't have many exceptions but I certainly have hundreds of thousands of Oban jobs, I think I can also handle the analytics data.

Or, maybe an alternative would be a second Postgres DB separate for analytics.

Anyway, you've already investigated and I trust your decision to use DuckDB or Clickhouse, I'll stay tuned. Thanks!

**Comment by lalabuy948** [comment]
I think I found another good solution for postres users, since I'm using cqrs and writes / reads completely separated we can write requests to users postresql (using existing project repo) and then read data via duckdb postgres extension. Which will bring best from both worlds. 

```sql
ATTACH 'dbname=postgres user=postgres host=127.0.0.1' AS db (TYPE POSTGRES, READ_ONLY);
```

Up for now I really liked this one.

**Comment by jaimeiniesta** [comment]
Sounds cool, do you think that could be flexible enough to use the same repo or have another repo dedicated to analytics?

**Comment by lalabuy948** [comment]
I think that it will be in same repo, as I plan to keep it small and simple.

**Comment by lalabuy948** [comment]
Hi @jaimeiniesta , I'm going to close this issue up for now, let know if you face any difficulties with 0.2.0 release. Let's keep in touch over email, happy to assist with anything!
